### ISSUE TITLE
Improper token has been passed.

### ISSUE THREAD

**Issue by BlueTree242** [azaelgg/discord-nitro-sniper#10]
I get this error after I choose option 1. how to fix?

**Comment by BlueTree242** [comment]
I fixed by putting the token in main.py,  now I have this for too long..

![image](https://user-images.githubusercontent.com/69328929/107861598-8eab6100-6e4f-11eb-809a-2d6fba85b21e.png)

**Comment by Spinicle** [comment]
You have logged in, now to test if it works, go to any server and search 'discord.gift/' and take the link of a code that has been redeemed. Then send it to yourself in a private channel. If anything comes up in the console of the sniper, it means its working.

**Comment by BlueTree242** [comment]
Thx, but is this bannable?

**Comment by Spinicle** [comment]
> 
> 
> Thx, but is this bannable?

Usage of self-bots or snipers are against discords TOS, so yes you might get banned from discord under the right circumstances. It includes if discord checks your account, if you claim to many nitros at once or even get reported.
